name: Update Last Update Date

on: push

jobs:
  update_date:
    name: Update Last Updated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@master

      - name: Run checks on links
        run: bash update_last_updated.sh

      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'